/**
 * Intent lexicon: Iraqi dialect, MSA, English and common Kurdish phrasings all
 * map onto the same intent ids. These are *aliases for intents*, never canned
 * answers — the answer is always produced from real order/catalogue data.
 */

import type { SupportIntent } from "./types";

export const INTENT_PHRASES: Record<SupportIntent, string[]> = {
  greeting: ["مرحبا", "اهلا", "هلا", "سلام", "هاي", "شلونك", "صباح الخير", "hello", "hi", "سلاو"],
  thanks: ["شكرا", "شكرن", "مشكور", "تسلم", "ممنون", "thanks", "thank you", "سوپاس"],
  human_agent: [
    "ادمن",
    "الادمن",
    "موظف",
    "انسان",
    "الدعم",
    "احد",
    "كلمني",
    "اتصل",
    "مسؤول",
    "admin",
    "support",
    "agent",
    "human",
  ],
  order_status: [
    "حالة الطلب",
    "حالة طلبي",
    "طلبي",
    "الطلب",
    "اوردر",
    "شنو صار",
    "شصار",
    "وين صار",
    "order",
    "status",
    "داواکاری",
  ],
  order_where: [
    "وين طلبي",
    "وين وصل",
    "متى يوصل",
    "الشحن",
    "التوصيل",
    "الدليفري",
    "where is my order",
    "shipping",
  ],
  payment_how: [
    "طرق الدفع",
    "كيف ادفع",
    "شلون ادفع",
    "زين كاش",
    "زينكاش",
    "ماستر كارد",
    "فيزا",
    "تحويل",
    "حوالة",
    "payment",
    "pay",
  ],
  payment_receipt: ["الوصل", "الايصال", "الوصولات", "رفعت الوصل", "دفعت", "receipt", "paid"],
  delivery_address: ["عنوان", "العنوان", "محافظة", "منطقة", "اضافة عنوان", "address"],
  account_credentials: [
    "بيانات الحساب",
    "الحساب",
    "الايميل",
    "البريد",
    "الباسورد",
    "كلمة المرور",
    "الرمز السري",
    "credentials",
    "account details",
  ],
  account_login_problem: [
    "لا يعمل الحساب",
    "ماكو حساب",
    "مايدخل",
    "ما يدخل",
    "الباس غلط",
    "خطا بالباسورد",
    "لا استطيع تسجيل الدخول",
    "مشكله بالدخول",
    "خربان",
    "wrong password",
    "cant login",
    "login error",
  ],
  game_not_opening: [
    "مايفتح",
    "ما تفتح",
    "لا تعمل اللعبه",
    "اللعبه ما تشتغل",
    "تطلب انترنت",
    "تحتاج انترنت",
    "اوفلاين",
    "يطلع ايرور",
    "ايرور",
    "خطا",
    "not opening",
    "crash",
    "error",
  ],
  primary_device: ["الجهاز الرئيسي", "بريمري", "primary", "نقل الحساب", "جهاز ثاني"],
  verification_code: ["رمز التحقق", "كود التحقق", "يطلب كود", "verification code", "otp"],
  refund_cancel: ["استرجاع", "الاسترداد", "الغاء", "ريفند", "ارجاع المبلغ", "refund", "cancel"],
  price_question: ["سعر", "بكم", "كم سعر", "ارخص", "الاسعار", "price", "how much"],
  product_search: ["ابحث", "تبحث", "عندكم", "متوفر", "العاب", "لعبه", "search", "available"],
  banana_wallet: ["الموز", "بنانا", "المحفظه", "نقاط", "سوق الموز", "banana", "wallet"],
  warranty: ["الضمان", "ضمان", "warranty"],
  tried_already: [
    "جربت",
    "مانفع",
    "ما نفع",
    "نفس الشي",
    "بردو",
    "لم تحل",
    "لم تُحل",
    "still not working",
    "didnt work",
    "same problem",
  ],
  unknown: [],
};

/** Words that mean "this is about a game/account item" for entity resolution. */
export const ITEM_HINTS = ["لعبه", "لعبة", "اللعبه", "game", "حساب", "الحساب", "account"];

/** Words that mean "this is about physical hardware". */
export const HARDWARE_HINTS = [
  "جهاز",
  "الجهاز",
  "سويتش",
  "switch",
  "دراع",
  "يد",
  "كنترول",
  "controller",
  "اكسسوار",
  "حافظه",
  "hardware",
];
