/**
 * Intent lexicon: Iraqi dialect, MSA, English and common Kurdish phrasings all
 * map onto the same intent ids. These are *aliases for intents*, never canned
 * answers — the answer is always produced from real order/catalogue data.
 */

import type { SupportIntent } from "./types";

export const INTENT_PHRASES: Record<SupportIntent, string[]> = {
  greeting: [
    "مرحبا",
    "اهلا",
    "هلا",
    "سلام",
    "هاي",
    "شلونك",
    "صباح الخير",
    "مساء الخير",
    "أهلاً",
    "أهلاً بك",
    "hello",
    "hi",
    "hey",
    "good morning",
    "good evening",
    "greetings",
    "silav",
    "slaw",
    "merheba",
    "merhaba",
    "selam",
    "gunaydin",
  ],
  thanks: [
    "شكرا",
    "شكرن",
    "مشكور",
    "تسلم",
    "ممنون",
    "يعطيك العافية",
    "thanks",
    "thank you",
    "thx",
    "appreciate it",
    "سوپاس",
    "dest xweş",
    "teşekkürler",
    "tesekkur",
    "sağol",
  ],
  human_agent: [
    "ادمن",
    "الادمن",
    "موظف",
    "انسان",
    "الدعم",
    "احد",
    "كلمني",
    "اتصل",
    "مسؤول",
    "تحدث مع الدعم",
    "تحدث مع الإدارة",
    "الدعم البشري",
    "تواصل مع الدعم",
    "admin",
    "support",
    "agent",
    "human",
    "live support",
    "talk to support",
    "talk to admin",
    "representative",
    "piştgiriya zindî",
    "bi piştgiriyê re biaxive",
    "rêvebir",
    "canlı destek",
    "destekle görüş",
    "yetkili",
    "müşteri temsilcisi",
  ],
  order_status: [
    "حالة الطلب",
    "حالة طلبي",
    "طلبي",
    "الطلب",
    "اوردر",
    "شنو صار",
    "شصار",
    "وين صار",
    "order",
    "my order",
    "order status",
    "track order",
    "where is my order",
    "dawa",
    "rewşa siparîşê",
    "siparîş",
    "sipariş",
    "sipariş durumu",
    "siparişim nerede",
  ],
  order_where: [
    "وين طلبي",
    "وين وصل",
    "متى يوصل",
    "الشحن",
    "التوصيل",
    "الدليفري",
    "delivery",
    "shipping",
    "delivery time",
    "şandin",
    "teslimat",
    "kargo",
    "ne zaman gelir",
  ],
  payment_how: [
    "طرق الدفع",
    "كيف ادفع",
    "شلون ادفع",
    "زين كاش",
    "زينكاش",
    "ماستر كارد",
    "فيزا",
    "تحويل",
    "حوالة",
    "المصرف العراقي",
    "fib",
    "اسيا باي",
    "بينانس",
    "يو اس دي تي",
    "payment",
    "how to pay",
    "payment methods",
    "zaincash",
    "asiapay",
    "binance",
    "usdt",
    "credit card",
    "çawa bidim",
    "rêyên dravdanê",
    "nasıl öderim",
    "ödeme yöntemleri",
    "odeme",
  ],
  payment_receipt: [
    "الوصل",
    "الايصال",
    "الوصولات",
    "رفعت الوصل",
    "دفعت",
    "وصل التحويل",
    "receipt",
    "invoice",
    "paid",
    "uploaded receipt",
    "wergirtin",
    "dekont",
    "ödeme yaptım",
  ],
  delivery_address: [
    "عنوان",
    "العنوان",
    "محافظة",
    "منطقة",
    "اضافة عنوان",
    "عنوان التوصيل",
    "بغداد",
    "اربيل",
    "البصرة",
    "address",
    "shipping address",
    "delivery address",
    "adû",
    "navnîşan",
    "adres",
    "teslimat adresi",
  ],
  account_credentials: [
    "بيانات الحساب",
    "الحساب",
    "الايميل",
    "البريد",
    "الباسورد",
    "كلمة المرور",
    "الرمز السري",
    "credentials",
    "account details",
    "login details",
    "password",
    "email",
    "şîfre",
    "hesab",
    "hesap bilgileri",
    "şifre",
    "giriş bilgileri",
  ],
  account_login_problem: [
    "لا يعمل الحساب",
    "ماكو حساب",
    "مايدخل",
    "ما يدخل",
    "الباس غلط",
    "خطا بالباسورد",
    "لا استطيع تسجيل الدخول",
    "مشكله بالدخول",
    "خربان",
    "wrong password",
    "cant login",
    "login error",
    "cannot sign in",
    "hesab naxebite",
    "têketin nabe",
    "şifre yanlış",
    "giriş yapamıyorum",
    "hesap açılmıyor",
  ],
  game_not_opening: [
    "مايفتح",
    "ما تفتح",
    "لا تعمل اللعبه",
    "اللعبه ما تشتغل",
    "تطلب انترنت",
    "تحتاج انترنت",
    "اوفلاين",
    "يطلع ايرور",
    "ايرور",
    "خطا",
    "not opening",
    "game crash",
    "black screen",
    "error code",
    "needs internet",
    "lîstik venabe",
    "oyun açılmıyor",
    "hata veriyor",
    "internet istiyor",
  ],
  primary_device: [
    "الجهاز الرئيسي",
    "بريمري",
    "primary",
    "primary console",
    "نقل الحساب",
    "جهاز ثاني",
    "ana cihaz",
    "primary switch",
  ],
  verification_code: [
    "رمز التحقق",
    "كود التحقق",
    "يطلب كود",
    "رمز الامان",
    "verification code",
    "otp",
    "security code",
    "2fa",
    "two step",
    "koda pejirandinê",
    "doğrulama kodu",
    "güvenlik kodu",
  ],
  refund_cancel: [
    "استرجاع",
    "الاسترداد",
    "الغاء",
    "ريفند",
    "ارجاع المبلغ",
    "الغاء الطلب",
    "refund",
    "cancel",
    "cancellation",
    "money back",
    "vegerandin",
    "iptal",
    "iade",
  ],
  price_question: [
    "سعر",
    "بكم",
    "كم سعر",
    "ارخص",
    "الاسعار",
    "شكد السعر",
    "price",
    "how much",
    "cost",
    "rates",
    "biha",
    "çend e",
    "fiyat",
    "kaç para",
    "ne kadar",
  ],
  product_search: [
    "ابحث",
    "تبحث",
    "عندكم",
    "متوفر",
    "العاب",
    "لعبه",
    "اكسسوارات",
    "ملحقات",
    "احدث الاكسسوارات",
    "تصفح الالعاب",
    "يد تحكم",
    "جوي كون",
    "كفر",
    "شاحن",
    "قاعدة",
    "search",
    "available",
    "browse",
    "browse games",
    "latest accessories",
    "accessories",
    "accessory",
    "controller",
    "joycon",
    "joy-con",
    "dock",
    "case",
    "memory card",
    "sd card",
    "lêgerîn",
    "lîstik",
    "aksesor",
    "ara",
    "oyunlar",
    "aksesuarlar",
    "en yeni aksesuarlar",
    "oyunlara göz at",
    "kumanda",
    "kol",
  ],
  banana_wallet: [
    "الموز",
    "بنانا",
    "المحفظه",
    "نقاط",
    "سوق الموز",
    "تعبئة المحفظة",
    "رصيد",
    "رصيد المحفظة",
    "ارغب بتعبئة رصيد المحفظة",
    "banana",
    "wallet",
    "top up wallet",
    "banana market",
    "balance",
    "cizdan",
    "mûz",
    "cüzdan",
    "bakiye",
    "muz",
    "bakiye yükle",
  ],
  warranty: ["الضمان", "ضمان", "كفالة", "warranty", "guarantee", "garantî", "garanti", "güvence"],
  tried_already: [
    "جربت",
    "مانفع",
    "ما نفع",
    "نفس الشي",
    "بردو",
    "لم تحل",
    "لم تُحل",
    "ما زالت المشكلة",
    "still not working",
    "didn't work",
    "didnt work",
    "tried that",
    "same issue",
    "same problem",
    "çareser nebû",
    "işe yaramadı",
    "hala çalışmıyor",
  ],
  unknown: [],
};

/** Words that mean "this is about a game/account item" for entity resolution. */
export const ITEM_HINTS = ["لعبه", "لعبة", "اللعبه", "game", "حساب", "الحساب", "account"];

/** Words that mean "this is about physical hardware". */
export const HARDWARE_HINTS = [
  "جهاز",
  "الجهاز",
  "سويتش",
  "switch",
  "دراع",
  "يد",
  "كنترول",
  "controller",
  "اكسسوار",
  "حافظه",
  "hardware",
];
